# SPDX-FileCopyrightText: 2025 The Wallet Ecosystem Authors
#
# SPDX-License-Identifier: CC0-1.0

tls:
  certificates:
    - certFile: /etc/traefik/certs/wallet-cert.pem
      keyFile: /etc/traefik/certs/wallet-key.pem
  options:
    default:
      minVersion: "VersionTLS12"
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
