# Manual workflow for running tests against our sandbox

name: Manual sandbox tests

on:
  workflow_dispatch:

jobs:
  echo-something:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Running manual workflow test"
